### ISSUE TITLE
 Failed to fetch Slasher address

### ISSUE THREAD

**Issue by FuturisticWizard** [Layr-Labs/eigenlayer-cli#109]
When im trying to register operator im getting error : 
command :  eigenlayer operator register operator.yaml
✅ Operator configuration file read successfully ****************************************
✅ Operator configuration file validated successfully ******************************************
? Enter password to decrypt the ecdsa private key: *************
Failed to fetch Slasher address: Post "https://eth-goerli.g.alchemy.com/v2/*****-TGo6uXBnh7ynizHVm-13c94jeN": dial tcp: lookup eth-goerli.g.alchemy.com on 127.0.0.53:53: no such host
  edit: after changing alchemy rpc from goerli to sepolia im getting error : 
 Failed to fetch Slasher address: no contract code at given address

**Comment by shrimalmadhur** [comment]
Hello. Goerli is deprecated and we have deployed on Holesky! Please use Holesky for testnet operations
