### ISSUE TITLE
invalid yaml file: with error invalid image mime-type. only png is supported

### ISSUE THREAD

**Issue by FuturisticWizard** [Layr-Labs/eigenlayer-cli#209]
**Describe the bug**
After executing command : 
```
eigenlayer operator register operator.yaml
```

![Zrzut ekranu 2024-09-10 144543](https://github.com/user-attachments/assets/48ac8116-e550-4a95-a889-bf286e24cd00)

**OS details**
Linux Ubuntu 22

**Comment by shrimalmadhur** [comment]
@FuturisticWizard can you share your image url you are using. seems that is no actually `png`

**Comment by FuturisticWizard** [comment]
my metadata file : 
```
{
  "name": "EigenNode",
  "website": "https://www.eigennode.com",
  "description": "best eigen node on the network",
  "logo": "https://github.com/FuturisticWizard/eigenlayer-/blob/main/Nextjs.png",
  "twitter": "https://twitter.com/futuristicWizard"
}
``` 
 I have used Nextjs logo file, was on hand ;p

**Comment by shrimalmadhur** [comment]
you might want to use raw github image instead of github.com link. for your image - [https://raw.githubusercontent.com/FuturisticWizard/eigenlayer-/main/Nextjs.png](https://raw.githubusercontent.com/FuturisticWizard/eigenlayer-/main/Nextjs.png) - try this and see if this works

**Comment by FuturisticWizard** [comment]
yes, that was it , now it went through but  I have another error :
```
insufficient funds for transfer
```   
I have 0.5 sepoliaEth

**Comment by FuturisticWizard** [comment]
yes, that was it , now it went through
