### ISSUE TITLE
Optional rewards claim flag: --ignore-tokens-not-found

### ISSUE THREAD

**Issue by youfoundron** [Layr-Labs/eigenlayer-cli#220]
I have multiple addresses, securing multiple AVS’s, earning rewards in potentially multiple tokens.

When I submit a rewards claim I tend to list all the possible tokens for any of these addresses.

As a result I am getting the error: failed to generate claim proof for earner: `token not found for token <missing-token> and earner <my-earner-address>`

Would it be possible to ignore any tokens that are not found and build a proof that includes the ones that are?

Potentially as a flag `--ignore-tokens-not-found` like so:

```
rewards claim
  --claim-timestamp latest_active
  --earner-address <my-earner-address>
  --eth-rpc-url https://mainnet.infura.io/v3/my-infura-id
  --network mainnet
  --output-type json
  --token-addresses
    0xBA50933C268F567BDC86E1aC131BE072C6B0b71a,
    0xec53bF9167f50cDEB3Ae105f56099aaaB9061F83,
    0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
  --ignore-tokens-not-found
```

**Comment by youfoundron** [comment]
Alternately, you could use no flag and modify the default behavior of the `--token-addresses` flag:

no tokens specified = claim all tokens found in the latest snapshot
tokens specified = claim only the tokens specified, throw if a token is not found

**Comment by shrimalmadhur** [comment]
thanks for reporting. great suggestion. We will work on this.
