### ISSUE TITLE
Generate smart contract details for delegationApprover for stakers

### ISSUE THREAD

**Issue by aivarasko** [Layr-Labs/eigenlayer-cli#232]
**Is your feature request related to a problem? Please describe.**
If delegateTo method is protected by using delegationApprover it can be non trivial to generate details for delegateTo method. 

**Describe the solution you'd like**
Would prefer to have command to generate details from operator environment using:
`eigenlayer operator delegate-to <configuration-file> <staker-address>`

**Comment by shrimalmadhur** [comment]
#233
