### ISSUE TITLE
HIghlight during key creation to save private key hex

### ISSUE THREAD

**Issue by shrimalmadhur** [Layr-Labs/eigenlayer-cli#29]
**Is your feature request related to a problem? Please describe.**
Currently we show private key and message to users while key creation that please save the key. it's not well highlighted

**Describe the solution you'd like**
We want to highlight that and make it more visible
- Make it bold
- add emojis, color etc?

**Describe alternatives you've considered**

**Additional context**

**Comment by DanielBoye** [comment]
Hello, I would like to work on this issue 😄 

I will make it bold with green text and add the 🔒 emoji 

After that I will research the possibility of doing the TODO in the code: 
```
// TODO: display it using `less` of `vi` so that it is not saved in terminal history
```

**Comment by DanielBoye** [comment]
It now looks like this 

![image](https://github.com/Layr-Labs/eigenlayer-cli/assets/83395536/a5f8f6c3-a04d-4a84-abdb-9a6808c7283c)

Will research the possibility of using `less` and `vi`
