### ISSUE TITLE
Run eigenlayer-cli have a problem Failed to fetch Slasher address {"err": "401 Unauthorized: project id required in the url\n"}

### ISSUE THREAD

**Issue by paycrypto609** [Layr-Labs/eigenlayer-cli#66]
eigenlayer operator register operator.yaml
✅ Operator configuration file read successfully 0xAeb66247Fb4fc9b0e2C86c34649e027a0e7295FF
✅ Operator configuration file validated successfully 0xAeb66247Fb4fc9b0e2C86c34649e027a0e7295FF
? Enter password to decrypt the ecdsa private key: ****************************************************************
2024-03-01T18:59:50.494+0800	ERROR	logging/zap_logger.go:57	Failed to fetch Slasher address	{"err": "401 Unauthorized: project id required in the url\n"}
github.com/Layr-Labs/eigensdk-go/logging.(*ZapLogger).Error
	/Users/qianjinmo/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.1.0/logging/zap_logger.go:57
github.com/Layr-Labs/eigensdk-go/chainio/utils.NewEigenlayerContractBindings
	/Users/qianjinmo/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.1.0/chainio/utils/bindings.go:45
github.com/Layr-Labs/eigensdk-go/chainio/clients/elcontracts.BuildELChainWriter
	/Users/qianjinmo/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.1.0/chainio/clients/elcontracts/writer.go:80
github.com/Layr-Labs/eigenlayer-cli/pkg.OperatorCmd.RegisterCmd.func1
	/Users/qianjinmo/Downloads/eigenlayer-cli-master/pkg/operator/register.go:98
github.com/urfave/cli/v2.(*Command).Run
	/Users/qianjinmo/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
	/Users/qianjinmo/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*Command).Run
	/Users/qianjinmo/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
	/Users/qianjinmo/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
	/Users/qianjinmo/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
	/Users/qianjinmo/Downloads/eigenlayer-cli-master/cmd/eigenlayer/main.go:34
runtime.main
	/usr/local/go/src/runtime/proc.go:271
401 Unauthorized: project id required in the url

**Comment by shrimalmadhur** [comment]
seems like you ethereum rpc node is invalid. can you make sure it works and you are authorized to access it?

**Comment by shrimalmadhur** [comment]
closing this since this is stale.
