### ISSUE TITLE
Why did the transaction never go through? Should you continue to use goerli now?

### ISSUE THREAD

**Issue by Cafexss** [Layr-Labs/eigenlayer-cli#79]
Why did the transaction never go through? Should you continue to use goerli now?
![image](https://github.com/Layr-Labs/eigenlayer-cli/assets/13113185/9a7a067e-6ab0-4a3a-b0c8-854170cfbbe0)

**Comment by shrimalmadhur** [comment]
Please migrate everything to holesky now. I am closing this issue since we support holesky.
