### ISSUE TITLE
operator.yaml The gas cost adjustment setting is not found in operator.yaml. Can it be increased?

### ISSUE THREAD

**Issue by tangyuan12** [Layr-Labs/eigenlayer-cli#83]
https://github.com/Layr-Labs/eigenlayer-cli/blob/master/pkg/operator/config/operator-config-example.yaml#L24
Gas cost adjustment setting not found in operator.yaml. Can it be increased?
I've also encountered this problem, and I suspect it's a gas bill issue.
![image](https://github.com/Layr-Labs/eigenlayer-cli/assets/22127762/de2dcbe8-b175-4a7e-a9cf-99b2d33ac395)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by shrimalmadhur** [comment]
Yea we don't have this feature implemented yet. I will put this in our backlog to implement this. thanks for asking

**Comment by shrimalmadhur** [comment]
we recently implemented it - and this should bump gas price now. Feel free to open if it still doesn't work
