### ISSUE TITLE
operator register piped password ?

### ISSUE THREAD

**Issue by svax974** [Layr-Labs/eigenlayer-cli#84]
Hello,

Is there any way I can pipe password into the "operator register" command like it is possible for key creation ?
(echo "password" | eigenlayer operator keys create --key-type ecdsa [keyname])

It doesn't seem to work, when I try to pipe passord I get : 
✅ Operator configuration file validated successfully 0x5c72439cb7eaDbB877c23bD3fFc8e88dc5316148
? Enter password to decrypt the ecdsa private key: Error while reading ecdsa key password
EOF
^[[48;204R^[[48;52R%                                                                                                                                                                                        

Thanks !

**Comment by shrimalmadhur** [comment]
What version are you using? It should work in the latest version of eigenlayer-cli. Try updating and then pipe should work.

**Comment by svax974** [comment]
Thanks for your reply.
I updated from git and rebuilt, result is still the same.
Piping into an "operator keys create" command works but not with an "operator register" command.

**Comment by shrimalmadhur** [comment]
our CI actually runs this test by piping and that seems to be working so i should work.  can you verify the version please?

**Comment by svax974** [comment]
I was using 0.6.3 but I just pulled again and used 0.7.0. Must have been a bug related to that version.
It is working now, thanks !
