### ISSUE TITLE
Operator registration transaction at: TX+✅

### ISSUE THREAD

**Issue by omiDBaghi** [Layr-Labs/eigenlayer-cli#86]
The link has been intertwined with ✅, leading to the wrong destination.

![Untitled](https://github.com/Layr-Labs/eigenlayer-cli/assets/3645938/baa1c461-a73e-4f59-bd41-f84e0cbbf28b)

**Comment by shrimalmadhur** [comment]
Good catch. I will update this soon. Thanks
